### ISSUE TITLE
missing mapper for widget GoogleColumn

### ISSUE THREAD

**Issue by Steve-O-Cassels** [findmypast/dashee#1]
Steps to reproduce:

Run against Titan/config/dasher.yml

![image](https://user-images.githubusercontent.com/3726727/35724575-20781dc6-07f6-11e8-94b1-6000332ebccc.png)

**Comment by AtebMT** [comment]
Yeah, I was aware of that. Do you have a working Dasher example of that dashboard. Everytime I looked it was broken. 😞

**Comment by AtebMT** [comment]
OK. Found a Titan dashboard that used `GoogleColumn` and v1.4 of Dashee now supports `GoogleColumn` transformations from dasher.
